module.exports = {
  namespace: 'asyncExport',
  arguments: [
    ['article', '0', '文章'],
    ['matter', '1', '事项'],
    ['scene', '2', '场景'],
    ['policy', '3', '政策'],
    ['policyWords', '4', '百科词条'],
    ['convenienceService', '5', '服务'],
    ['project', '6', '项目'],
    ['synonym', '7', '问答'],
    ['institution', '8', '机构'],
    ['chatLibrary', '9', '聊天库'],
    ['bannedWord', '10', '垃圾词'],
    ['dictionary', '11', '字典'],
    ['portraitTag', '12', '画像标签'],
    ['functionWord', '13', '功能词'],
    ['splitMaterial', '14', '分解材料'],
    ['standardField', '15', '标准字段'],
    ['standardMaterial', '16', '标准材料'],
    ['policyExplain', '19', '政策解读'],
    ['matterHandleGuide', '20', '网上办事指引'],
    ['hotline', '21', '热线电话'],
    ['messageStatistic', '22', '消息统计'],
  ],
};
