// 备份 暂时不会用到了

const { authEnum } = require('./authEnum');
const iframePagesEnum = require('./iframePagesEnum');
const { summaryInfoRoutes } = require('./summaryInfoRoutes');

const routes_bak = text => [
  {
    path: '/',
    redirect: '/content/policyKnowledgeLib/policyContent',
  },
  {
    path: '/login',
    component: '../layouts/UserLayout',
    routes: [
      {
        name: 'login',
        path: '/login',
        component: './user/login',
      },
    ],
  },
  {
    path: '/redirect',
    component: './redirectPage',
  },
  {
    path: '/test',
    component: './test',
  },
  {
    path: '/testLayout',
    component: './testLayout',
  },
  {
    authority: [authEnum.content],
    path: '/content',
    name: '内容运营',
    header: true,
    icon: 'HddOutlined',
    component: '../layouts/SecurityLayout',
    routes: [
      {
        path: '/',
        component: '../layouts/PageLayout',
        routes: [
          {
            path: '/content',
            redirect: '/content/policyKnowledgeLib/policyContent',
          },
          {
            authority: [authEnum.themeManage],
            path: '/content/connect',
            name: '主题接入管理',
            icon: 'RobotOutlined',
            routes: [
              {
                path: '/content/connect',
                redirect: '/content/connect/themeAccess',
              },
              {
                authority: [authEnum.themeAccess],
                path: '/content/connect/themeAccess',
                name: '业务梳理',
                component: './themeAccess',
              },
              {
                authority: [authEnum.themeAudit],
                path: '/content/connect/themeAudit',
                name: '梳理确认',
                component: './themeAudit',
              },
              {
                authority: [authEnum.infoLibrary],
                path: '/content/connect/infoLibrary',
                name: '基本信息库',
                component: './infoLibrary',
              },
              {
                path: '/content/connect/infoLibrary/viewInfo',
                name: '查看信息',
                hideInMenu: true,
                component: './infoLibrary/ViewInfo',
              },
              {
                path: '/content/connect/infoLibrary/editInfo',
                name: '编辑信息',
                hideInMenu: true,
                component: './infoLibrary/EditInfo',
              },
              {
                path: '/content/connect/infoLibrary/createInfo',
                name: '创建信息',
                hideInMenu: true,
                component: './infoLibrary/createInfoLibrary',
              },
            ],
          },
          {
            authority: [authEnum.themeOperation],
            path: '/content/do',
            name: '主题管理',
            icon: 'AuditOutlined',
            routes: [
              {
                path: '/content/do',
                redirect: '/content/do/scenes',
              },
              {
                authority: [authEnum.matters],
                path: '/content/do/matters',
                name: '事项管理',
                component: './matters',
              },
              {
                authority: authEnum.matters_edit_alias,
                path: '/content/do/matters/new',
                name: '事项管理/新增',
                hideInMenu: true,
                component: './matters/MatterForm',
              },
              {
                authority: authEnum.matters_edit_alias,
                path: '/content/do/matters/edit/:matterid',
                name: '事项管理/编辑',
                hideInMenu: true,
                component: './matters/EditMatter',
              },
              {
                authority: [authEnum.matters],
                path: '/content/do/matters/view/:matterid',
                name: '事项管理/查看',
                hideInMenu: true,
                component: './matters/ViewMatter',
              },
              {
                path: '/content/do/matters/materialSplit/:type/:id', // 事项-材料拆解
                hideInMenu: true,
                component: './matters/materialSplit',
              },
              {
                path: '/content/do/matters/formSplit/:id', // 事项-材料拆解
                hideInMenu: true,
                component: './matters/formSplit',
              },
              {
                path: '/content/do/matters/formCopy/:id', // 事项-材料拆解
                hideInMenu: true,
                component: './matters/formCopy',
              },
              {
                authority: [authEnum.matters_bluk],
                path: '/content/do/matters/bulk',
                hideInMenu: true,
                component: './matters/bulk',
              },
              {
                authority: [authEnum.mattersSync],
                path: '/content/do/matters/matterSync',
                name: '事项同步',
                component: './matterSync',
              },
              {
                authority: [authEnum.materialSplit],
                path: '/content/do/materialSplit',
                name: '材料拆解',
                component: './materialSplit',
              },
              {
                authority: [authEnum.scenes],
                path: '/content/do/scenes',
                name: '主题管理',
                component: './scenes',
              },
              {
                authority: authEnum.scenes_edit_alias,
                path: '/content/do/scenes/sceneinfo',
                component: './scenes/editScenes',
                name: '主题管理/新增',
                hideInMenu: true,
              },
              {
                authority: [authEnum.scenes],
                path: '/content/do/scenes/view/:sceneId',
                component: './scenes/ViewScenePage',
                name: '主题管理/查看',
                hideInMenu: true,
              },
              {
                authority: authEnum.scenes_edit_alias,
                path: '/content/do/scenes/editScenes/:sceneId',
                component: './scenes/EditScenePage',
                name: '主题管理/编辑',
                hideInMenu: true,
              },
              {
                authority: [authEnum.scenes_bluk],
                path: '/content/do/scenes/bulk',
                component: './scenes/bulk',
                name: '主题管理/批量操作',
                hideInMenu: true,
              },
              {
                path: '/content/do/scenesQA',
                name: '引导问卷',
                hideInMenu: true,
                component: './scenesQA',
              },
              {
                path: '/content/do/scenesQA/:scenesId',
                hideInMenu: true,
                redirect: '/content/do/scenesQA/:scenesId/none',
              },
              {
                authority: [authEnum.scenes],
                path: '/content/do/scenesQA/:scenesId/:nodeId',
                hideInMenu: true,
                component: './scenesQA',
              },

              {
                authority: [authEnum.scenesAudit],
                path: '/content/do/scenesAudit',
                name: '主题审核',
                component: './scenesAudit',
              },
              {
                authority: [authEnum.scenesAudit],
                path: '/content/do/scenesAudit/view/:sceneId',
                name: '主题审核/查看',
                component: './scenes/ViewScenePage',
                hideInMenu: true,
              },
              {
                authority: [authEnum.scenesAudit],
                path: '/content/do/scenesAudit/audit/:sceneId',
                name: '主题审核/审核',
                component: './scenesAudit/AuditPage',
                hideInMenu: true,
              },
              {
                path: '/content/do/scenes/conditions/:sceneId',
                hideInMenu: true,
                redirect: '/content/do/scenes/conditions/:sceneId/none',
              },
              {
                path: '/content/do/scenes/conditions/:sceneId',
                name: '主题办理条件',
                hideInMenu: true,
                component: './scenes/handlingConditions',
              },
              {
                path: '/content/do/scenes/conditions/:sceneId/:nodeId',
                name: '主题办理条件/节点',
                hideInMenu: true,
                component: './scenes/handlingConditions',
              },

              {
                authority: [authEnum.oneFormManager],
                path: '/content/do/oneFormManager',
                name: '一表管理',
                component: './jumpPage',
              },
              {
                authority: [authEnum.oneMatter],
                path: '/content/do/oneMatter',
                name: '主题专栏', // 原 一事联办
                component: './oneMatter',
              },
              {
                authority: [authEnum.oneMatter],
                path: '/content/do/oneMatter/create',
                name: '主题专栏/新增', // 原 一事联办
                component: './oneMatter/editOneMatter',
                hideInMenu: true,
              },
              {
                authority: [authEnum.oneMatter],
                path: '/content/do/oneMatter/view/:oneMatterId',
                name: '主题专栏/查看', // 原 一事联办
                component: './oneMatter/ViewOneMatterPage',
                hideInMenu: true,
              },
              {
                authority: [authEnum.oneMatter],
                path: '/content/do/oneMatter/edit/:oneMatterId',
                name: '主题专栏/编辑', // 原 一事联办
                component: './oneMatter/EditOneMatterPage',
                hideInMenu: true,
              },
            ],
          },
          {
            authority: [authEnum.policyKnowledgeLib],
            path: '/content/policyKnowledgeLib',
            name: '政务知识库',
            icon: 'ContainerOutlined',
            routes: [
              {
                path: '/content/policyKnowledgeLib',
                redirect: '/content/policyKnowledgeLib/policyContent',
              },
              {
                authority: [authEnum.policyContent],
                path: '/content/policyKnowledgeLib/policyContent',
                name: '政策原文',
                component: './policyContent',
              },
              {
                path: '/content/policyKnowledgeLib/policyGraph',
                name: '政策图谱',
                component: './policyGraph',
              },
              {
                path: '/content/policyKnowledgeLib/policyGraph/bulk',
                hideInMenu: true,
                component: './policyGraph/bulk',
              },
              {
                path: '/content/policyKnowledgeLib/policyContent/new',
                name: '新增政策',
                component: './policyContent/policyContentForm',
                hideInMenu: true,
              },
              {
                path: '/content/policyKnowledgeLib/policyContent/edit/:policyId',
                name: '编辑政策',
                component: './policyContent/EditPolicyContent',
                hideInMenu: true,
              },
              {
                path: '/content/policyKnowledgeLib/policyContent/view/:policyId',
                name: '查看政策',
                component: './policyContent/ViewPolicyContent',
                hideInMenu: true,
              },
              {
                authority: [authEnum.policyContent],
                path: '/content/policyKnowledgeLib/policyContent/bulk',
                component: './policyContent/bulk',
                name: '政策正文/批量操作',
                hideInMenu: true,
              },
              {
                authority: [authEnum.policyContent],
                path: '/content/policyKnowledgeLib/policyContent/bulk/:id',
                component: './policyContent/bulk',
                name: '政策正文/重复政策批量操作',
                hideInMenu: true,
              },

              {
                authority: [authEnum.policyWord],
                path: '/content/policyKnowledgeLib/policyWords',
                name: '政务百科词条',
                component: './policyWords',
              },
              {
                authority: [authEnum.institutionManage],
                path: '/content/policyKnowledgeLib/institutionManage',
                name: '部门信息',
                component: './institutionManage',
              },
              {
                authority: authEnum.institutionManage_edit_alias,
                path: '/content/policyKnowledgeLib/institutionManage/edit/:id',
                name: '机构编辑',
                hideInMenu: true,
                component: './institutionManage/EditInstitution',
              },
              {
                authority: [authEnum.institutionManage],
                path: '/content/policyKnowledgeLib/institutionManage/view/:id',
                name: '机构查看',
                hideInMenu: true,
                component: './institutionManage/ViewInstitution',
              },
              {
                authority: authEnum.institutionManage_edit_alias,
                path: '/content/policyKnowledgeLib/institutionManage/create',
                name: '机构新增',
                hideInMenu: true,
                component: './institutionManage/EditInstitution',
              },
              {
                authority: [authEnum.article],
                path: '/content/policyKnowledgeLib/article',
                name: text['通知公告'],
                component: './article',
              },
              {
                path: '/content/policyKnowledgeLib/article/create',
                name: '文章管理/添加',
                hideInMenu: true,
                component: './article/editArticleForm',
              },
              {
                path: '/content/policyKnowledgeLib/article/edit/:articleId',
                name: '文章管理/编辑',
                hideInMenu: true,
                component: './article/EditArticle',
              },
              {
                path: '/content/policyKnowledgeLib/article/view/:articleId',
                name: '文章管理/查看',
                hideInMenu: true,
                component: './article/ViewArticle',
              },
              {
                authority: [authEnum.service],
                path: '/content/policyKnowledgeLib/service',
                name: '服务管理',
                component: './serviceMenu',
              },
              {
                authority: authEnum.service_edit_alias,
                path: '/content/policyKnowledgeLib/service/serviceinfo',
                name: '服务管理/新增服务管理',
                component: './serviceMenu/editService',
                hideInMenu: true,
              },
              {
                authority: [authEnum.service],
                path: '/content/policyKnowledgeLib/service/serviceinfo/:serviceid',
                name: '服务管理/查看服务管理',
                component: './serviceMenu/EditServicePage',
                hideInMenu: true,
              },
              {
                authority: authEnum.service_edit_alias,
                path: '/content/policyKnowledgeLib/service/serviceinfo/:serviceid',
                name: '服务管理/编辑服务管理',
                component: './serviceMenu/EditServicePage',
                hideInMenu: true,
              },
              {
                authority: [authEnum.service_bulk],
                path: '/content/policyKnowledgeLib/service/bulk',
                name: '服务管理/批量操作',
                component: './serviceMenu/bulk',
                hideInMenu: true,
              },
              {
                authority: authEnum.projectManage_edit_alias,
                path: '/content/policyKnowledgeLib/projectManage/edit/:id',
                name: '项目管理/编辑项目管理',
                component: './projectManage/EditProject',
                hideInMenu: true,
              },
              {
                authority: [authEnum.projectManage],
                path: '/content/policyKnowledgeLib/projectManage',
                name: '申报项目',
                component: './projectManage',
              },
              /*{
                path: '/content/policyKnowledgeLib/projectView',
                name: '项目一览',
                component: './projectView',
              },
              {
                path: '/content/policyKnowledgeLib/projectView/create',
                name: '新增项目一览',
                component: './projectView/projectViewForm',
                hideInMenu: true,
              },
              {
                path: '/content/policyKnowledgeLib/projectView/edit/:id',
                name: '编辑项目一览',
                component: './projectView/projectViewForm',
                hideInMenu: true,
              },
              {
                path: '/content/policyKnowledgeLib/projectView/view/:id',
                name: '查看项目一览',
                component: './projectView/projectViewForm',
                hideInMenu: true,
              },*/
              {
                path: '/content/policyKnowledgeLib/projectManage/projectExam/:id',
                name: '项目体检',
                component: './projectExam',
                hideInMenu: true,
              },
              {
                authority: authEnum.projectManage_edit_alias,
                path: '/content/policyKnowledgeLib/projectManage/create',
                name: '项目管理新增',
                component: './projectManage/compontents/CreateProject',
                hideInMenu: true,
              },
              {
                authority: [authEnum.projectManage],
                path: '/content/policyKnowledgeLib/projectManage/view/:id',
                name: '项目管理查看',
                component: './projectManage/ViewProject',
                hideInMenu: true,
              },
              {
                authority: authEnum.projectManage_edit_alias,
                path: '/content/policyKnowledgeLib/projectManage/projectExam/:id',
                name: '项目管理体检',
                component: './projectExam',
                hideInMenu: true,
              },
              {
                authority: [authEnum.policyProjectSync],
                path: '/content/policyKnowledgeLib/policyProjectSync',
                name: '政策项目同步',
                component: './policyProjectSync',
              },
              {
                authority: [authEnum.synonyms],
                path: '/content/policyKnowledgeLib/synonyms',
                name: '常见问题',
                component: './synonyms',
              },
              {
                authority: [authEnum.synonyms],
                path: '/content/policyKnowledgeLib/synonyms/view',
                name: '问答管理/查看',
                hideInMenu: true,
                component: './synonyms/createOrEditQuestionForm/getFormData',
              },
              {
                authority: authEnum.synonyms_edit_alias,
                path: '/content/policyKnowledgeLib/synonyms/edit',
                name: '问答管理/编辑',
                hideInMenu: true,
                component: './synonyms/createOrEditQuestionForm/getFormData',
              },
              {
                authority: authEnum.synonyms_edit_alias,
                path: '/content/policyKnowledgeLib/synonyms/create',
                name: '问答管理/创建',
                hideInMenu: true,
                component: './synonyms/createOrEditQuestionForm/getFormData',
              },
              {
                authority: [authEnum.policyExplain],
                path: '/content/policyKnowledgeLib/policyExplain',
                name: '政策解读',
                component: './policyExplain',
              },
              {
                authority: authEnum.policyContent_edit_alias,
                path: '/content/policyKnowledgeLib/policyExplain/create',
                name: '政策解读/创建',
                hideInMenu: true,
                component: './policyExplain/policyExplainForm',
              },
              {
                authority: authEnum.policyContent_edit_alias,
                path: '/content/policyKnowledgeLib/policyExplain/edit/:policyExplainId',
                name: '政策解读/编辑',
                hideInMenu: true,
                component: './policyExplain/EditPolicyExplain',
              },
              {
                authority: [authEnum.policyExplain],
                path: '/content/policyKnowledgeLib/policyExplain/view/:policyExplainId',
                name: '政策解读/查看',
                hideInMenu: true,
                component: './policyExplain/ViewPolicyExplain',
              },
              {
                authority: [authEnum.hotline],
                path: '/content/policyKnowledgeLib/hotline',
                name: '热线电话',
                component: './hotline',
              },
              {
                authority: authEnum.hotline_edit_alias,
                path: '/content/policyKnowledgeLib/hotline/create',
                name: '热线电话/创建',
                hideInMenu: true,
                component: './hotline/hotlineForm',
              },
              {
                authority: authEnum.hotline_edit_alias,
                path: '/content/policyKnowledgeLib/hotline/edit/:hotlineId',
                name: '热线电话/编辑',
                hideInMenu: true,
                component: './hotline/EditHotline',
              },
              {
                authority: [authEnum.hotline],
                path: '/content/policyKnowledgeLib/hotline/view/:hotlineId',
                name: '热线电话/查看',
                hideInMenu: true,
                component: './hotline/ViewHotline',
              },
              /* 网上办事指引 */
              {
                authority: [authEnum.matterHandleGuide],
                path: '/content/policyKnowledgeLib/matterHandleGuide',
                name: '网上办事指引',
                component: './matterHandleGuide',
              },
              {
                authority: authEnum.matterHandleGuide_edit_alias,
                path: '/content/policyKnowledgeLib/matterHandleGuide/edit',
                name: '网上办事指引/创建',
                hideInMenu: true,
                component: './matterHandleGuide/EditMatterHandleGuide',
              },
              {
                authority: authEnum.matterHandleGuide_edit_alias,
                path: '/content/policyKnowledgeLib/matterHandleGuide/edit/:id',
                name: '网上办事指引/编辑',
                hideInMenu: true,
                component: './matterHandleGuide/EditMatterHandleGuide',
              },
              {
                authority: [authEnum.matterHandleGuide],
                path: '/content/policyKnowledgeLib/matterHandleGuide/view/:id',
                name: '网上办事指引/查看',
                hideInMenu: true,
                component: './matterHandleGuide/ViewMatterHandleGuide',
              },
              {
                authority: [authEnum.smartQa],
                path: `/content/policyKnowledgeLib/smartQa`,
                target: 'qaGuide',
                name: '智能小申',
                component: './IframePagesWithConfig',
              },
            ],
          },
          {
            authority: [authEnum.reviewPoint],
            path: '/content/reviewPoint',
            name: '审查要素库',
            icon: 'InboxOutlined',
            component: './reviewPoint',
          },
          {
            path: '/content/reviewPoint/specialStep/:matterId',
            component: './reviewPoint/specialStepList',
            hideInMenu: true,
          },
          {
            path: '/content/reviewPoint/applyConditionList/:matterId',
            component: './reviewPoint/applyConditionList',
            hideInMenu: true,
          },
          {
            path: '/content/reviewPoint/applyMaterialList/:matterId',
            component: './reviewPoint/applyMaterialList',
            hideInMenu: true,
          },
          {
            path: '/content/reviewPoint/formCheckPoint/:matterId',
            component: './reviewPoint/formCheckPoint',
            hideInMenu: true,
          },
          {
            authority: [authEnum.qaManage],
            path: '/content/ask',
            name: '问答运营',
            icon: 'CommentOutlined',
            routes: [
              {
                path: '/content/ask',
                redirect: '/content/ask/emoticon',
              },
              {
                authority: [authEnum.emoticon],
                path: '/content/ask/emoticon',
                name: '表情包管理',
                component: './emoticonManage',
              },
              {
                authority: [authEnum.dimensionManage],
                path: '/content/ask/dimensionManage',
                name: '维度管理',
                component: './dimension',
              },
              {
                authority: [authEnum.hotWords],
                path: '/content/ask/hotWordsManage',
                name: '热词管理',
                component: './hotWords',
              },
              {
                authority: [authEnum.hotWords],
                path: '/content/ask/hotWordsManage/commonQuestion',
                name: '常用问句',
                hideInMenu: true,
                component: './commonQuestion',
              },
              {
                authority: [authEnum.synonymsSetting],
                path: '/content/ask/synonymsSetting',
                name: '问答设置',
                component: './synonymsSetting',
              },
              {
                authority: [authEnum.chatLibrary],
                path: '/content/ask/chatLibrary',
                name: '聊天库',
                component: './chatLibrary',
              },
              {
                authority: [authEnum.chatLibrary],
                path: '/content/ask/chatLibrary/view',
                name: '聊天库查看',
                hideInMenu: true,
                component: './chatLibrary/chatForm/view',
              },
              {
                authority: authEnum.chatLibrary_edit_alias,
                path: '/content/ask/chatLibrary/add',
                name: '新增聊天库',
                hideInMenu: true,
                component: './chatLibrary/chatForm',
              },
              {
                authority: authEnum.chatLibrary_edit_alias,
                path: '/content/ask/chatLibrary/edit',
                name: '编辑聊天库',
                hideInMenu: true,
                component: './chatLibrary/chatForm',
              },
              {
                authority: [authEnum.hotQuestion],
                path: '/content/ask/hotQuestion',
                name: '热门问题',
                component: './hotQuestion/hotQa',
              },
              {
                authority: [authEnum.hotQuestion],
                path: '/content/ask/hotQuestion/hotMatter',
                name: '热门事项',
                hideInMenu: true,
                component: './hotQuestion/hotMatter',
              },
              {
                authority: [authEnum.hotQuestion],
                path: '/content/ask/hotQuestion/hotScene',
                name: '热门场景',
                hideInMenu: true,
                component: './hotQuestion/hotScene',
              },
              {
                authority: [authEnum.hotQuestion],
                path: '/content/ask/hotQuestion/hotPolicy',
                name: '热门政策',
                hideInMenu: true,
                component: './hotQuestion/hotPolicy',
              },
              {
                authority: [authEnum.hotQuestion],
                path: '/content/ask/hotQuestion/hotService',
                name: '热门服务',
                hideInMenu: true,
                component: './hotQuestion/hotService',
              },
              {
                authority: [authEnum.hotQuestion],
                path: '/content/ask/hotQuestion/hotProject',
                name: '热门项目',
                hideInMenu: true,
                component: './hotQuestion/hotProject',
              },
              {
                authority: [authEnum.qaRefresh],
                path: '/content/ask/refresh',
                name: '刷新',
                component: './refresh',
              },
              {
                authority: [authEnum.triggerWords],
                path: '/content/ask/triggerWords',
                name: '触发词管理',
                component: './triggerWords',
              },
              {
                authority: [authEnum.functionWords],
                path: '/content/ask/functionWords',
                name: '功能词管理',
                component: './functionWord',
              },
              {
                authority: [authEnum.professionalWords],
                path: '/content/ask/professionalWords',
                name: '专业词管理',
                component: './professionalWords',
              },
              {
                path: '/content/ask/professionalWords/bulk',
                name: '专业词管理/批量删除',
                hideInMenu: true,
                component: './professionalWords/bulk',
              },
              {
                path: '/content/ask/professionalWords/create',
                name: '新增专业词',
                hideInMenu: true,
                component: './professionalWords/CerateProfessionalWords',
              },
              {
                path: '/content/ask/professionalWords/edit/:id',
                name: '编辑专业词',
                hideInMenu: true,
                component: './professionalWords/EditProfessionalWords',
              },
              {
                path: '/content/ask/professionalWords/view/:id',
                name: '查看专业词',
                hideInMenu: true,
                component: './professionalWords/ViewProfessionalWords',
              },
              {
                authority: [authEnum.rubbishWords],
                path: '/content/ask/rubbishWords',
                name: '垃圾词管理',
                component: './rubbishWords',
              },
              {
                authority: [authEnum.rubbishWords],
                path: '/content/ask/rubbishWordsMaintain',
                name: '垃圾词-词条类型维护',
                hideInMenu: true,
                component: './rubbishWords/WordsMaintain',
              },
              {
                path: '/content/ask/dialogManager',
                name: '对话管理',
                component: './dialogManager',
              },
              {
                path: '/content/ask/dialogManager/:id',
                hideInMenu: true,
                component: './dialogStudios',
              },
            ],
          },

          {
            authority: [authEnum.archiveManage],
            path: '/content/archivesLibMenu',
            name: '用户档案库',
            icon: 'FileSearchOutlined',
            routes: [
              {
                path: '/content/archivesLibMenu',
                redirect: `/content/archivesLibMenu/archivesLib`,
              },
              {
                authority: [authEnum.archiveLib],
                path: `/content/archivesLibMenu/archivesLib`,
                target: iframePagesEnum.ARCHIVESLIB,
                name: '档案库',
                component: './IframePages',
              },
              {
                authority: [authEnum.menuSetting],
                path: `/content/archivesLibMenu/menuSetting`,
                name: '菜单配置',
                component: './menuSetting',
              },
              {
                authority: [authEnum.standardMaterial],
                path: '/content/archivesLibMenu/standardMaterial',
                name: '标准材料管理',
                component: './standardMaterial',
              },
              {
                authority: authEnum.standardMaterial_edit_alias,
                path: '/content/archivesLibMenu/standardMaterial/new',
                name: '新增标准材料库',
                hideInMenu: true,
                component: './standardMaterial/EditStandardMaterial',
              },
              {
                authority: authEnum.standardMaterial_edit_alias,
                path: '/content/archivesLibMenu/standardMaterial/edit/:materialId',
                name: '编辑标准材料库',
                hideInMenu: true,
                component: './standardMaterial/EditStandardMaterial',
              },
              {
                authority: [authEnum.standardMaterial],
                path: '/content/archivesLibMenu/standardMaterial/view/:materialId',
                name: '查看标准材料库',
                hideInMenu: true,
                component: './standardMaterial/ViewStandardMaterial',
              },
              {
                authority: [authEnum.standardFieldStore],
                path: '/content/archivesLibMenu/standardFieldStore',
                name: '标准字段管理',
                component: './standardFieldStore',
              },
              {
                authority: authEnum.standardFieldStore_edit_alias,
                path: '/content/archivesLibMenu/standardFieldStore/create',
                name: '新增标准字段',
                component: './standardFieldStore/fieldStoreForm',
                hideInMenu: true,
              },
              {
                authority: authEnum.standardFieldStore_edit_alias,
                path: '/content/archivesLibMenu/standardFieldStore/edit/:fieldId',
                name: '编辑标准字段',
                component: './standardFieldStore/EditStandardField',
                hideInMenu: true,
              },
              {
                authority: [authEnum.standardFieldStore],
                path: '/content/archivesLibMenu/standardFieldStore/view/:fieldId',
                name: '查看标准字段',
                component: './standardFieldStore/ViewStandardField',
                hideInMenu: true,
              },
            ],
          },

          {
            authority: [authEnum.efficacy],
            path: '/content/efficacy',
            name: '主题效能管理',
            icon: 'RiseOutlined',
            routes: [
              {
                authority: [authEnum.themeOpen],
                path: '/content/efficacy/open',
                name: '主题开通统计',
                component: './building',
              },
              {
                authority: [authEnum.themeDo],
                path: '/content/efficacy/do',
                name: '主题办件统计',
                component: './building',
              },
            ],
          },

          {
            authority: [authEnum.workOrder],
            path: '/content/knowledgeLibWorkOrder',
            name: text['知识库工单'],
            icon: 'ExceptionOutlined',
            routes: [
              {
                path: '/content/knowledgeLibWorkOrder',
                redirect: `/content/knowledgeLibWorkOrder/commit`,
              },
              {
                authority: [authEnum.workOrderCommit],
                path: '/content/knowledgeLibWorkOrder/commit',
                name: '工单上报',
                component: './knowledgeLibWorkOrder/workOrderCommit',
              },
              {
                authority: [authEnum.workOrderConfirm],
                path: '/content/knowledgeLibWorkOrder/confirm',
                name: '工单确认',
                component: './knowledgeLibWorkOrder/workOrderConfirm',
              },
              {
                authority: [authEnum.workOrderCommit],
                path: '/content/knowledgeLibWorkOrder/commit/create',
                name: '工单创建',
                component: './knowledgeLibWorkOrder/EditWorkOrder',
                hideInMenu: true,
              },
              {
                authority: [authEnum.workOrderCommit],
                path: '/content/knowledgeLibWorkOrder/commit/view/:workOrderId',
                name: '工单上报列表/查看',
                component: './knowledgeLibWorkOrder/ViewWorkOrder',
                hideInMenu: true,
              },
              {
                authority: [authEnum.workOrderConfirm],
                path: '/content/knowledgeLibWorkOrder/confirm/view/:workOrderId',
                name: '工单确认列表/查看',
                component: './knowledgeLibWorkOrder/ViewWorkOrder',
                hideInMenu: true,
              },
              {
                authority: [authEnum.workOrderCommit],
                path: '/content/knowledgeLibWorkOrder/commit/edit/:workOrderId',
                name: '工单上报列表/编辑',
                component: './knowledgeLibWorkOrder/workOrderCommit/CommitForm',
                hideInMenu: true,
              },
              {
                authority: [authEnum.workOrderConfirm],
                path: '/content/knowledgeLibWorkOrder/confirm/edit/:workOrderId',
                name: '工单确认列表/编辑',
                component: './knowledgeLibWorkOrder/workOrderConfirm/AuditForm',
                hideInMenu: true,
              },
              {
                authority: [authEnum.workOrderConfirm],
                path: '/content/knowledgeLibWorkOrder/confirm/audit/:workOrderId',
                name: '工单审核',
                component: './knowledgeLibWorkOrder/workOrderConfirm/AuditForm',
                audit: true,
                hideInMenu: true,
              },
              {
                authority: [authEnum.workOrderKnowledge],
                path: '/content/knowledgeLibWorkOrder/knowledge',
                name: '知识库接口',
                component: './knowledgeInter',
              },
            ],
          },

          {
            authority: [authEnum.portraitMenu],
            path: '/content/portraitMenu',
            name: '用户画像库',
            icon: 'UserOutlined',
            routes: [
              {
                path: '/content/portraitMenu',
                redirect: '/content/portraitMenu/tags',
              },
              {
                authority: [authEnum.tagManage],
                path: '/content/portraitMenu/tags',
                name: '标签管理',
                component: './portraitTags',
              },
              {
                authority: authEnum.tagManage_edit_alias,
                path: '/content/portraitMenu/tags/editTag',
                name: '标签管理/新增',
                hideInMenu: true,
                component: './portraitTags/CreatePortraitTagPage',
              },
              {
                authority: authEnum.tagManage_edit_alias,
                path: '/content/portraitMenu/tags/editTag/:tagId',
                name: '标签管理/编辑',
                hideInMenu: true,
                component: './portraitTags/EditPortraitTagPage',
              },
              {
                authority: [authEnum.tagManage],
                path: '/content/portraitMenu/tags/view/:tagId',
                name: '标签管理/查看',
                hideInMenu: true,
                component: './portraitTags/ViewPortraitTagPage',
              },
              {
                authority: [authEnum.tagManage],
                path: '/content/portraitMenu/tags/bulk',
                name: '标签管理/批量',
                hideInMenu: true,
                component: './portraitTags/bulk',
              },
              {
                authority: [authEnum.tagManage],
                path: '/content/portraitMenu/tags/bulkAdd',
                name: '标签管理/批量新增',
                hideInMenu: true,
                component: './portraitTags/bulk/bulkAdd',
              },
              {
                authority: [authEnum.portraitSelf],
                path: '/content/portraitMenu/portraitSelf',
                name: '用户管理-个人',
                component: './portraitSelf',
              },
              {
                path: '/content/portraitMenu/portraitSelf/view/:id',
                name: '用户管理-个人-查看更多',
                hideInMenu: true,
                component: './portraitSelf/compontents/ViewPortraitSelf',
              },
              {
                path: '/content/portraitMenu/portraitSelf/edit/:id',
                name: '用户管理-个人-编辑',
                hideInMenu: true,
                component: './portraitSelf/EditPortraitSelf',
              },
              {
                path: '/content/portraitMenu/portraitSelf/bulk',
                name: '用户管理-个人-批量操作',
                hideInMenu: true,
                component: './portraitSelf/bulk',
              },
              {
                authority: [authEnum.portraitLegal],
                path: '/content/portraitMenu/portraitLegal',
                name: '用户管理-法人',
                component: './portraitLegal',
              },
              {
                path: '/content/portraitMenu/portraitLegal/view/:id',
                name: '用户管理-法人-查看更多',
                hideInMenu: true,
                component: './portraitLegal/compontents/ViewPortraitLegal',
              },
              {
                path: '/content/portraitMenu/portraitLegal/edit/:id',
                name: '用户管理-法人-编辑',
                hideInMenu: true,
                component: './portraitLegal/EditPortraitLegal',
              },
              {
                path: '/content/portraitMenu/portraitLegal/bulk',
                name: '用户管理-个人-批量操作',
                hideInMenu: true,
                component: './portraitSelf/bulk',
              },
              {
                authority: [authEnum.ruleManage],
                path: '/content/portraitMenu/ruleManage',
                name: '规则管理',
                component: './ruleManage',
              },
              {
                authority: [authEnum.tableManage],
                path: '/content/portraitMenu/tableManage',
                name: '库表管理',
                component: './tableManage',
              },
              {
                authority: [authEnum.tableManage],
                path: '/content/portraitMenu/tableManage/view/:tableId',
                name: '库表查看',
                component: './tableManage/ViewTableManage',
                hideInMenu: true,
              },
              {
                authority: authEnum.tableManage_edit_alias,
                path: '/content/portraitMenu/tableManage/edit/:tableId',
                name: '库表编辑',
                component: './tableManage/EditTableManage',
                hideInMenu: true,
              },
              {
                authority: authEnum.tableManage_edit_alias,
                path: '/content/portraitMenu/tableManage/new',
                name: '库表新增',
                component: './tableManage/EditTableManage',
                hideInMenu: true,
              },
              {
                authority: [authEnum.minimalCondition],
                path: '/content/portraitMenu/minimalCondition',
                name: '最小条件',
                component: './minimalCondition',
              },
              {
                path: '/content/portraitMenu/minimalCondition/bulk',
                name: '最小条件批量操作',
                component: './minimalCondition/bulk',
                hideInMenu: true,
              },
              {
                path: '/content/portraitMenu/minimalCondition/view/:id',
                name: '最小条件/查看',
                component: './minimalCondition/ViewMinimalCondition',
                hideInMenu: true,
              },
              {
                path: '/content/portraitMenu/minimalCondition/edit/:id',
                name: '最小条件/编辑',
                component: './minimalCondition/EditMinimalCondition',
                hideInMenu: true,
              },
              {
                authority: [authEnum.ruleManage],
                path: '/content/portraitMenu/ruleManage/funcEditor',
                component: './ruleManage/FuncEditor',
                hideInMenu: true,
              },
              {
                authority: [authEnum.ruleManage],
                path: '/content/portraitMenu/ruleManage/funcCreate',
                component: './ruleManage/FuncEditor',
                name: '新增函数',
                hideInMenu: true,
              },
              {
                authority: [authEnum.ruleManage],
                path: '/content/portraitMenu/ruleManage/funcView',
                component: './ruleManage/FuncEditor',
                name: '查看函数',
                hideInMenu: true,
              },
              {
                authority: [authEnum.ruleManage],
                path: '/content/portraitMenu/ruleManage/condition',
                name: '条件管理',
                component: './condition',
                hideInMenu: true,
              },
              {
                authority: [authEnum.tagAudit],
                path: '/content/portraitMenu/tagsAudit',
                name: '标签审核',
                component: './portraitTagsAudit',
              },
              {
                authority: [authEnum.tagManage],
                path: '/content/portraitMenu/tagsAudit/view/:tagId',
                name: '查看审核标签的详情',
                component: './portraitTagsAudit/ViewPortraitTagDetail',
                hideInMenu: true,
              },
              {
                authority: [authEnum.tagManage],
                path: '/content/portraitMenu/tagsAudit/review/:tagId',
                name: '审核标签的详情',
                component: './portraitTagsAudit/ReviewPortraitTagDetail',
                hideInMenu: true,
              },
              {
                authority: [authEnum.tagManage],
                path: '/content/portraitMenu/tagsAudit/edit/:tagId',
                name: '编辑审核标签的内容',
                component: './portraitTagsAudit/EditPortraitTagDetail',
                hideInMenu: true,
              },
              {
                authority: [authEnum.tagSync],
                path: '/content/portraitMenu/tagsSync',
                name: '标签同步',
                component: './portraitTagsSync',
              },
              {
                authority: [authEnum.tagSync],
                path: '/content/portraitMenu/tagsSync/:pageTab',
                name: '标签同步/列表',
                component: './portraitTagsSync/TableContentWrap',
                hideInMenu: true,
              },
              {
                authority: [authEnum.outputModule],
                path: '/content/portraitMenu/outputModule',
                name: '输出管理',
                component: './outputModule',
              },
              {
                authority: authEnum.outputModule_edit_alias,
                path: '/content/portraitMenu/outputModule/add',
                name: '输出模块/新增',
                hideInMenu: true,
                component: './outputModule/outputModuleForm',
              },
              {
                authority: authEnum.outputModule_edit_alias,
                path: '/content/portraitMenu/outputModule/edit',
                name: '输出模块/编辑',
                hideInMenu: true,
                component: './outputModule/outputModuleForm',
              },
              {
                authority: [authEnum.outputModule],
                path: '/content/portraitMenu/outputModule/view',
                name: '输出模块/查看',
                hideInMenu: true,
                component: './outputModule/outputModuleForm',
              },
              // {
              //   authority: [authEnum.recommendTest],
              //   path: '/content/portraitMenu/recommendTest',
              //   name: '推荐测试',
              //   component: './recommendTest',
              // },
              {
                authority: [authEnum.paramsManage],
                path: '/content/portraitMenu/displayPosition',
                name: '参数管理',
                component: './displayPosition/components/sourceManage',
              },
              {
                path: '/content/portraitMenu/displayPosition/freshRegular',
                name: '规则刷新',
                hideInMenu: true,
                component: './displayPosition/components/FreshRegular',
              },
              {
                path: '/content/portraitMenu/displayPosition/sourceManage',
                name: '来源管理',
                hideInMenu: true,
                component: './displayPosition/components/sourceManage',
              },
            ],
          },
          {
            authority: [authEnum.sceneData],
            path: '/content/sceneDataReuse',
            name: '场景用数',
            icon: 'BorderOuterOutlined',
            routes: [
              {
                path: '/content/sceneDataReuse',
                redirect: '/content/sceneDataReuse/sceneDataReuseManage',
              },
              {
                authority: [authEnum.sceneDataManage],
                path: '/content/sceneDataReuse/sceneDataReuseManage',
                name: '场景用数管理',
                component: './sceneDataUse',
              },
              {
                path: '/content/sceneDataReuse/sceneDataReuseManage/create',
                name: '场景用数新增',
                hideInMenu: true,
                component: './sceneDataUse/EditSceneData',
              },
              {
                path: '/content/sceneDataReuse/sceneDataReuseManage/edit/:id',
                name: '场景用数编辑',
                hideInMenu: true,
                component: './sceneDataUse/EditSceneData',
              },
              {
                path: '/content/sceneDataReuse/sceneDataReuseManage/view/:id',
                name: '场景用数查看',
                hideInMenu: true,
                component: './sceneDataUse/ViewSceneData',
              },
            ],
          },
          {
            authority: [authEnum.recommendManage],
            path: '/content/recommendationMenu',
            name: '推荐管理',
            icon: 'FunctionOutlined',
            routes: [
              {
                path: '/content/recommendationMenu',
                redirect: '/content/recommendationMenu/modules',
              },
              {
                authority: [authEnum.modules],
                path: '/content/recommendationMenu/modules',
                name: '模块管理',
                component: './modulesManage',
              },
              {
                authority: authEnum.modules_edit_alias,
                path: '/content/recommendationMenu/modules/create',
                name: '新增模块管理',
                hideInMenu: true,
                component: './modulesManage/PreModuleForm',
              },
              {
                authority: authEnum.modules_edit_alias,
                path: '/content/recommendationMenu/modules/edit/:id',
                name: '编辑模块管理',
                hideInMenu: true,
                component: './modulesManage/EditModulePage',
              },
              {
                path: '/content/recommendationMenu/modules/view/:id',
                name: '查看模块管理',
                hideInMenu: true,
                component: './modulesManage/ViewModulePage',
              },
              {
                authority: [authEnum.strategy],
                path: '/content/recommendationMenu/strategy',
                name: '策略管理',
                component: './strategyManage',
              },
              {
                path: '/content/recommendationMenu/strategy/view/:id',
                name: '策略管理查看',
                hideInMenu: true,
                component: './strategyManage/ViewStrategy',
              },
              {
                authority: [authEnum.suggestTest],
                path: '/content/recommendationMenu/suggestTest',
                name: '推荐测试',
                component: './suggestTest',
              },
            ],
          },

          {
            authority: [authEnum.messageMenu],
            path: '/content/messageMenu',
            name: '消息中心',
            icon: 'MessageOutlined',
            routes: [
              {
                path: '/content/messageMenu',
                redirect: '/content/messageMenu/message',
              },
              {
                authority: [authEnum.message],
                path: '/content/messageMenu/message',
                name: '消息管理',
                component: './message',
              },
              {
                authority: [authEnum.message],
                path: '/content/messageMenu/message/view',
                name: '消息查看',
                hideInMenu: true,
                component: './message/handleMessageForm/getMessageFormData',
              },
              {
                authority: authEnum.message_edit_alias,
                path: '/content/messageMenu/message/edit',
                name: '消息编辑',
                hideInMenu: true,
                component: './message/handleMessageForm/getMessageFormData',
              },
              {
                authority: authEnum.message_edit_alias,
                path: '/content/messageMenu/message/create',
                name: '消息创建',
                hideInMenu: true,
                component: './message/handleMessageForm/getMessageFormData',
              },
              {
                authority: authEnum.message_edit_alias,
                path: '/content/messageMenu/message/copy',
                name: '消息复制',
                hideInMenu: true,
                component: './message/handleMessageForm/getMessageFormData',
              },
              {
                path: '/content/messageMenu/messageManage',
                name: '消息列表',
                component: './messageManage',
              },
              {
                path: '/content/messageMenu/messageManage/edit',
                name: '编辑消息',
                hideInMenu: true,
                component: './messageManage/EditMessage',
              },
              {
                path: '/content/messageMenu/messageManage/view',
                name: '查看消息',
                hideInMenu: true,
                component: './messageManage/EditMessage',
              },
              {
                path: '/content/messageMenu/messageManage/create',
                name: '创建消息',
                hideInMenu: true,
                component: './messageManage/EditMessage',
              },
              {
                path: '/content/messageMenu/messageManage/copy',
                name: '复制消息',
                hideInMenu: true,
                component: './messageManage/EditMessage',
              },
              {
                path: '/content/messageMenu/warningManage',
                name: '提醒列表',
                component: './warningManage',
              },
              {
                path: '/content/messageMenu/warningManage/create',
                name: '新增提醒',
                hideInMenu: true,
                component: './warningManage/EditWarning',
              },
              {
                path: '/content/messageMenu/warningManage/edit',
                name: '编辑提醒',
                hideInMenu: true,
                component: './warningManage/EditWarning',
              },
              {
                path: '/content/messageMenu/warningManage/view',
                name: '查看提醒',
                hideInMenu: true,
                component: './warningManage/EditWarning',
              },
              {
                path: '/content/messageMenu/warningManage/copy',
                name: '复制提醒',
                hideInMenu: true,
                component: './warningManage/EditWarning',
              },
              {
                path: '/content/messageMenu/messageTemplate',
                name: '消息模板',
                component: './messageTemplate',
              },
              {
                path: '/content/messageMenu/messageTemplate/view/:id',
                hideInMenu: true,
                component: './messageTemplate/ViewMessageTemplate',
              },
              {
                path: '/content/messageMenu/messageTemplate/edit',
                hideInMenu: true,
                component: './messageTemplate/EditMessageTemplate',
              },
              {
                path: '/content/messageMenu/messageTemplate/edit/:id',
                hideInMenu: true,
                component: './messageTemplate/EditMessageTemplate',
              },
              {
                path: '/content/messageMenu/messageConfig',
                name: '消息设置',
                component: './messageConfig/MessageDivision',
              },
              {
                path: '/content/messageMenu/messageConfig/noticeStyle',
                name: '提醒样式',
                hideInMenu: true,
                component: './messageConfig/NoticeStyle',
              },
              {
                path: '/content/messageMenu/messageConfig/messageImg',
                name: '消息配图',
                hideInMenu: true,
                component: './messageConfig/MessageImg',
              },
              {
                path: '/content/messageMenu/messageConfig/authMethod',
                name: '认证方式',
                hideInMenu: true,
                component: './messageConfig/AuthMethod',
              },
              {
                path: '/content/messageMenu/messageConfig/otherConfig',
                name: '其他设置',
                hideInMenu: true,
                component: './messageConfig/OtherConfig',
              },
            ],
          },
          {
            authority: [authEnum.tool],
            path: '/content/tool',
            name: '工具菜单',
            icon: 'ToolOutlined',
            routes: [
              {
                path: '/content/tool',
                redirect: '/content/tool/dict',
              },
              {
                authority: [authEnum.dictManage],
                path: '/content/tool/dict',
                name: '字典管理',
                component: './dictManage',
              },
            ],
          },
          {
            authority: [authEnum.summaryInfo],
            path: '/content/summaryInfo',
            name: '统计信息',
            icon: 'BarChartOutlined',
            routes: summaryInfoRoutes,
          },
          {
            component: './404',
          },
        ],
      },
    ],
  },
  {
    authority: [authEnum.app],
    path: '/app',
    name: '应用运营',
    header: true,
    icon: 'CloudOutlined',
    component: '../layouts/SecurityLayout',
    routes: [
      {
        path: '/',
        component: '../layouts/PageLayout',
        routes: [
          {
            path: '/app',
            redirect: '/app/appManager/applicationAudit',
          },
          {
            authority: [authEnum.appManager],
            path: '/app/appManager',
            name: '主题应用接入',
            icon: 'AppstoreOutlined',
            routes: [
              {
                path: '/app/appManager',
                redirect: '/app/appManager/applicationAudit',
              },
              {
                authority: [authEnum.appRegister],
                path: '/app/appManager/appRegister',
                name: '应用注册',
                component: './appRegister',
              },
              {
                authority: [authEnum.applicationAudit],
                path: '/app/appManager/applicationAudit',
                name: '应用审核',
                component: './applicationAudit',
              },
            ],
          },
          {
            component: './404',
          },
        ],
      },
    ],
  },
  {
    authority: [authEnum.model],
    path: '/model',
    name: '模型运营',
    header: true,
    icon: 'BuildOutlined',
    component: '../layouts/SecurityLayout',
    routes: [
      {
        path: '/',
        component: '../layouts/PageLayout',
        routes: [
          {
            path: '/model',
            redirect: '/model/modelManager/commonModel',
          },
          {
            authority: [authEnum.modelManager],
            path: '/model/modelManager',
            name: '模型管理',
            icon: 'BlockOutlined',
            routes: [
              {
                path: '/model/modelManager',
                redirect: '/model/modelManager/commonModel',
              },
              {
                authority: [authEnum.commonModel],
                path: '/model/modelManager/commonModel',
                name: '公共模型',
                component: './commonModel',
              },
              {
                authority: [authEnum.subscription],
                path: '/model/modelManager/subscription',
                name: '订阅管理',
                component: './subscription',
              },
            ],
          },
          {
            path: '/model/questionnaire',
            icon: 'BulbOutlined',
            name: '问卷表单',
            component: './designQuestionnaire',
          },
          {
            path: '/model/oneform',
            icon: 'BulbOutlined',
            name: '主题表单',
            component: './designOneForm',
          },
          {
            component: './404',
          },
        ],
      },
      {
        component: './404',
      },
    ],
  },
  {
    authority: [authEnum.system],
    path: '/system',
    name: '系统管理',
    header: true,
    icon: 'SettingOutlined',
    component: '../layouts/SecurityLayout',
    routes: [
      {
        path: '/',
        component: '../layouts/PageLayout',
        routes: [
          {
            path: '/system',
            redirect: '/system/manager/users',
          },
          {
            path: '/system/manager',
            name: '系统管理',
            icon: 'SettingOutlined',
            authority: [authEnum.systemManage],
            routes: [
              {
                path: '/system/manager',
                redirect: '/system/manager/users',
              },
              {
                authority: [authEnum.users],
                path: '/system/manager/users',
                name: '账号管理',
                component: './userManager/users',
              },
              {
                path: '/system/manager/department',
                name: '部门管理',
                authority: [authEnum.department],
                component: './userManager/department',
              },
              {
                authority: [authEnum.role],
                path: '/system/manager/roles',
                name: '角色管理',
                component: './userManager/roles',
              },
              {
                authority: [authEnum.operatingManual],
                path: '/system/manager/operatingManual',
                name: '产品手册',
                component: './operatingManual',
              },
              {
                authority: [authEnum.taskManage],
                path: '/system/manager/taskManage',
                name: '任务管理',
                component: './taskManage',
              },
              {
                path: '/system/manager/taskManage/logs',
                name: '任务日志',
                component: './taskLogs',
                hideInMenu: true,
              },
            ],
          },
          {
            authority: [authEnum.systemConfig],
            path: '/system/systemConfig',
            name: '系统配置',
            icon: 'SlidersOutlined',
            routes: [
              {
                path: '/system/systemConfig',
                redirect: '/system/systemConfig/params',
              },
              {
                path: '/system/systemConfig/params',
                name: '系统参数配置',
                component: './systemParamsConfig',
              },
              {
                authority: [authEnum.auditChain],
                path: '/system/systemConfig/auditChain',
                name: '审核链配置',
                component: './auditChain',
              },
              {
                authority: [authEnum.departmentDict],
                path: '/system/systemConfig/dictDepartmentManage',
                name: '字典配置',
                component: './dictDepartmentManage',
              },
            ],
          },
          {
            component: './404',
          },
        ],
      },
      {
        component: './404',
      },
    ],
  },
  {
    component: './404',
  },
];

module.exports = routes_bak;
